import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./(system)/components/NavBar";
import NavBar from "./(system)/components/NavBar";
import { AuthProvider } from "./(system)/context/authContext";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <AuthProvider>
        
        {children}
        
        
        </AuthProvider>
      
      </body>
    </html>
  );
}
